context:
  name: docling-core
  version: 2.4.0
  python_min: "3.9" # remove this line once https://github.com/prefix-dev/rattler-build/pull/1122 is available

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/docling_core-${{ version }}.tar.gz
  sha256: 93f817b0105d564bbd334f8314b359b8a3fb234ec47b5013a020c9cb6ebd2e87

build:
  number: 1
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - validate = docling_core.utils.validate:main
      - generate_jsonschema = docling_core.utils.generate_jsonschema:main
      - generate_docs = docling_core.utils.generate_docs:main

requirements:
  host:
    - python ${{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - jsonschema >=4.16.0,<5.0.0
    - pydantic >=2.6.0,<3.0.0
    - jsonref >=1.1.0,<2.0.0
    - tabulate >=0.8.0,<0.10.0
    - pandas >=2.1.4,<3.0.0
    - pillow >=10.3.0,<11.0.0

tests:
  - python:
      imports:
        - docling_core
      pip_check: true
  - script:
      - validate --help
      - generate_jsonschema --help
      - generate_docs --help

about:
  summary: A python library to define and validate data types in Docling.
  license: MIT
  license_file: LICENSE
  homepage: https://ds4sd.github.io/

extra:
  recipe-maintainers:
    - hadim
