context:
  name: docling-core
  version: 2.3.1
  python_min: "3.9" # remove this line once https://github.com/prefix-dev/rattler-build/pull/1122 is available

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/docling_core-${{ version }}.tar.gz
  sha256: b32f588fc869b9cc633da7095fa8b8277b8f9f0f3e6c9e000f3e16266dc9599d

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - validate = docling_core.utils.validate:main
      - generate_jsonschema = docling_core.utils.generate_jsonschema:main
      - generate_docs = docling_core.utils.generate_docs:main

requirements:
  host:
    - python ${{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - jsonschema >=4.16
    - pydantic >=2.6
    - jsonref >=1.1
    - tabulate >=0.9
    - pandas >=2.1.4
    - pillow >=10.3

tests:
  - python:
      imports:
        - docling_core
      pip_check: false
  - script:
      - validate --help
      - generate_jsonschema --help
      - generate_docs --help

about:
  summary: A python library to define and validate data types in Docling.
  license: MIT
  license_file: LICENSE
  homepage: https://ds4sd.github.io/

extra:
  recipe-maintainers:
    - hadim
