context:
  name: docling-core
  version: "2.19.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/docling_core-${{ version }}.tar.gz
  sha256: ebf3062e31155bb5f0e6132056a2d239a0e6e693a75c5758886909bb9fef461a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - validate = docling_core.utils.validate:main
      - generate_jsonschema = docling_core.utils.generate_jsonschema:main
      - generate_docs = docling_core.utils.generate_docs:main
      - docling-view = docling_core.cli.view:app

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - jsonschema >=4.16.0,<5.0.0
    - pydantic >=2.6.0,<3.0.0
    - jsonref >=1.1.0,<2.0.0
    - tabulate >=0.9.0,<1.0.0
    - pandas >=2.1.4,<3.0.0
    - pillow >=10.0.0,<12.0.0
    - pyyaml >=5.1,<7.0.0
    - typing-extensions >=4.12.2,<5.0.0
    - transformers >=4.34.0,<5.0.0
    - semchunk >=2.2.0,<3.0.0
    - typer >=0.12.5,<0.13.0
    - latex2mathml >=3.77.0,<4.0.0

tests:
  - python:
      imports:
        - docling_core
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - validate --help
      - generate_jsonschema --help
      - generate_docs --help
      - docling-view --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: A python library to define and validate data types in Docling.
  license: MIT
  license_file: LICENSE
  homepage: https://ds4sd.github.io/

extra:
  recipe-maintainers:
    - hadim
